### PR TITLE
Prepare ustore builds to get the latest conan package from ustore-deps

### PR DESCRIPTION
**Pull request by gurgenyegoryan**

### CODE REVIEW

**Comment by ashvardanian** [comment]
@gurgenyegoryan, why do we build Google Test from source while taking the pre-compile Google Benchmark from Conan?

**Comment by gurgenyegoryan** [comment]
> @gurgenyegoryan, why do we build Google Test from source while taking the pre-compile Google Benchmark from Conan?

I have removed the Google Benchmark(gtest) from conanfile and build from source, because when I fetch from conan it gives an error with rocksdb. Now I want to update our prerelease and release - so that every time it takes the latest package from ustore-deps. To do this, it is necessary that there is no `gtest` in the conan package, so that there are no problems.

**Comment by ashvardanian** [comment]
@gurgenyegoryan, so is it a temporary workaround, that will be afterwards reverted?

**Comment by gurgenyegoryan** [comment]
> 

Yes, when there is a solution with the conan package gtest, then we will return to using gtest with conan.

**Pull request merged**
