### PR TITLE
Persistent Snapshots, Export/Import Tooling, and CLI

### PR DESCRIPTION
**Pull request by ashvardanian**

### CODE REVIEW

**Comment by ashvardanian** [comment]
@gurgenyegoryan, will the Docker build on `main` succeed once we merge?

@gurgenyegoryan and @DarvinHarutyunyan, please look at the `.yml` file and fix all the improper capitalization and inconsistent naming for pipeline stages.

Is the Python build for 1 platform with 1 Python version (3.10) normal to take over an hour, even with pre-compiled dependencies? Why is Java recompiling RocksDB?

**Comment by gurgenyegoryan** [comment]
> 

@ashvardanian Testing docker right now and write.

**Comment by ashvardanian** [comment]
@gurgenyegoryan, I am preparing to publish everything under the refreshed UStore name.

**Comment by ashvardanian** [comment]
@gurgenyegoryan, the release script doesn't preserve order and deploy docs before the Python package is built and shipped to PyPi.

**Comment by ashvardanian** [comment]
@gurgenyegoryan, the prerelease script is also wrong and assumes that the software runs on x86:

```yml
      - name: Install UStore dependencies using Conan
        run: |
          wget -q https://github.com/unum-cloud/ustore-deps/releases/download/v0.1.3/ustore_deps_x86_linux.tar.gz
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          tar -xzf ./ustore_deps_x86_linux.tar.gz -C ~/.conan
          conan install ustore_deps/0.12.1@unum/x86_linux -g cmake -s compiler.version=11
          rm -rf ./ustore_deps_x86_linux.tar.gz
```

What if the action runs on an Arm machine? Where are the pre-compiled Arm dependencies in `ustore-deps` releases?

**Comment by gurgenyegoryan** [comment]
> 



> @gurgenyegoryan, the prerelease script is also wrong and assumes that the software runs on x86:
> 
> ```yaml
>       - name: Install UStore dependencies using Conan
>         run: |
>           wget -q https://github.com/unum-cloud/ustore-deps/releases/download/v0.1.3/ustore_deps_x86_linux.tar.gz
>           conan profile new --detect default
>           conan profile update settings.compiler.libcxx=libstdc++11 default
>           tar -xzf ./ustore_deps_x86_linux.tar.gz -C ~/.conan
>           conan install ustore_deps/0.12.1@unum/x86_linux -g cmake -s compiler.version=11
>           rm -rf ./ustore_deps_x86_linux.tar.gz
> ```
> 
> What if the action runs on an Arm machine? Where are the pre-compiled Arm dependencies in `ustore-deps` releases?

I am working on it that with our CI ustore-deps to create packages on arm architectures. I have one package that I created manually in AWS and so far I use it only in Dockerfile. Soon there will be a CI for arm dependencies in ustore-deps.

**Pull request merged**
